---
language: php
php:
  - 5.3
  - 5.4
  - 5.5
branches:
  only:
    - master
before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
script: bin/phpunit
notifications:
  email:
    recipients:
      - developers@launchkey.com
      - gabe@ga.be
