language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - GUZZLE_VERSION=~3.0
  - GUZZLE_VERSION=dev-master

matrix:
  allow_failures:
    - php: hhvm
    - env: GUZZLE_VERSION=dev-master

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - composer require "guzzle/guzzle:${GUZZLE_VERSION}" --prefer-source

script: bin/phpunit

notifications:
  email:
    recipients:
      - developers@launchkey.com
