<?php
/**
 * @author Adam Englander <adam@launchkey.com>
 * @copyright 2015 LaunchKey, Inc. See project license for usage.
 */

namespace LaunchKey\SDK\Domain;

/**
 * Request the LaunchKey Engine to de-orbit the user session identified by the auth_request identified by the provided
 * request ID.
 *
 * @package LaunchKey\SDK\Domain
 */
class DeOrbitRequest
{
    /**
     * @var string auth_request auth_request value generated by the LaunchKey Engine API of the user session to
     * de-orbit.
     */
    private $requestId;

    /**
     * @param $requestId auth_request value generated by the LaunchKey Engine API of the user session to de-orbit.
     */
    public function __construct($requestId)
    {
        $this->requestId = $requestId;
    }

    /**
     * Get the auth_request value generated by the LaunchKey Engine API of the user session to de-orbit
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->requestId;
    }
}
